Attention vis
Jacob-Chmura/plausibility-vaccine pull request #71
Opened 2024-12-08 21:51 UTC by sebastian9991

Some visualizations for attention weights.

2024-12-08 21:53 UTC, sebastian9991 commented
Don't quite understand the difference between pytorch_adapter.bin & pytorch_model_head.bin. Used the latter for weights.

2024-12-08 21:56 UTC, sebastian9991 commented
Can add other visualization methods. e.g pca or compare cosine sim between paired adapters

2024-12-08 23:10 UTC, Jacob-Chmura reviewed
At the moment, these charts are not clear enough to add into the report, but it's a decent start. Have you looked at packages that do this for you? I just quickly found this one: https://github.com/jessevig/bertviz

The distribution plots are probably easier to get right, but they need to be contrasted across adapters. It may also be the case that to see any signal we need to condition on specific s-v-o samples to visualize are adapters firing. We need to think more about this

2024-12-08 23:10 UTC, Jacob-Chmura commented on figs/adapter_attention_weights/charts_attention_weights/opacity_pred_attention_weights.png
It's not clear how I am to interpret these charts, as you mentioned, some sort of dim reduction or smoothing combined with an explicit way to compare **between** adapters is the important part

2024-12-08 23:10 UTC, Jacob-Chmura commented on figs/adapter_attention_weights/charts_attention_weights/opacity_pred_attention_weights.png
what are these axes representing?

2024-12-08 23:10 UTC, Jacob-Chmura commented on figs/adapter_attention_weights/charts_attention_weights/weight_pred_attention_weights.png
Why does this one look so different?

2024-12-08 23:10 UTC, Jacob-Chmura commented on figs/adapter_attention_weights/hist_combined_weights/mobility_pred_combined_weights.png
In isolation these are not very useful. We need to compare between adapters, and try to see if we can highlight general distributional patterns

2024-12-08 23:10 UTC, Jacob-Chmura commented on scripts/analyze_attention_weights.py
> +    default='../weights/',
Can you please mimic my other scripts and make all these relative to the global root directory, and the resolve the paths as I have done, i.e.: https://github.com/Jacob-Chmura/plausibility-vaccine/blob/c1ac47817b351633a888545abb0b01b55582a2a5/scripts/generate_selectional_association_data.py#L46

2024-12-08 23:13 UTC, sebastian9991 commented on figs/adapter_attention_weights/hist_combined_weights/mobility_pred_combined_weights.png
Right. I'll try some other vis method to compare it.

2024-12-08 23:14 UTC, Jacob-Chmura requested changes
See me above comments for changes

2024-12-09 04:21 UTC, sebastian9991 commented
I was able to use bertviz. There is a single HTML output you can checkout in the /figs folder. I'll try what I mention about looking at attention on plausible/implausible sentences. I'll also look at ways to aggregate the results for better viewing. Bertviz seems like what would be best to use. I'll investigate it more. Pushing so you can see how it looks so far. 

I also tried a PCA method on a single adapter weight (not comparing them) It didn't reveal much to me. 


Note I skipped the trailing-whitespaces hook as it complained about the HTML file.

2024-12-09 04:23 UTC, sebastian9991 commented on scripts/analyze_attention_weights.py
> +    default='../weights/',
Changed it to that. Let me know if that's what you were looking for.

2024-12-12 13:39 UTC, Jacob-Chmura reviewed
Given our 5 page limit, and the relative importance of the other charts, I'm not sure this will end up going in the report unless we find a very interesting result. Otherwise, I think just the mispredictoins analysis will be sufficient for the discussion section.

2024-12-15 16:13 UTC, closed without merging